asyncapi: '2.0.0'
info:
  title: Webhook Events V2
  version: '2.13'
  description: |
    Delivery updates and inbound messages are sent out to you in a manner of events.

    They are sent to the callback URLs that you specified in a [Configuration](/conversations/current.html#configurations).

    Inbound messages are sent to your system as soon as we receive them from the channel.

    Delivery updates are sent to your system when:

    - a message reaches a final state, or
    - a message reaches an intermediate state and you opted-in to receive this, or
    - a user decides to delete a message previously sent **to** you (only available on WhatsApp).

    We treat

    - delivered
    - seen / read
    - finally failed

    as final states for messages sent by you.

    All other states are treated as intermediate states.

tags:
  - name: "Received messages"
    description: |
      Events emitted when the recipient of the message replies or deletes a previously sent message.
  - name: "Delivery updates"
    description: Events emitted on updates of message delivery.
  - name: "Calling"
    description: Events emitted when receiving messages or updates for WhatsApp Calling
servers:
  production:
    url: 78.110.226.11
    description: The server address of tyntec, the events originate from
    protocol: https
channels:
  "MoMessage (Basic)":
    description: |
      A message received by us and delivered to your system via a webhook provided by your system.
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/MoMessage'
      bindings:
        http:
          type: request
          method: POST
  "MoMessage (SMS)":
    description: |
      A message received by us on the SMS channel and delivered to your system via a webhook provided by your system.
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/SMSMoMessage'
      bindings:
        http:
          type: request
          method: POST
  "MoMessage (WhatsApp)":
    description: |
      A message received by us on the WhatsApp channel and delivered to your system via a webhook provided by your system.
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/WhatsAppMoMessage'
      bindings:
        http:
          type: request
          method: POST
  "MoMessage (Viber)":
    description: |
      A message received by us on the Viber channel and delivered to your system via a webhook provided by your system.
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/ViberMoMessage'
      bindings:
        http:
          type: request
          method: POST
  "MoMessage Postback":
    description: |
      Postbacks are triggered when a user clicks on a button or interacts with any element that supports this.

      The event is treated as a MoMessage event for the purpose of callback lookups.

      **Supporting channels**

      - WhatsApp: Quick Reply buttons
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/MoMessagePostback'
      bindings:
        http:
          type: request
          method: POST
  "MoMessage Order":
    description: |
      Orders are triggered when a user places an order from a pre-filled shopping cart.

      The event is treated as a MoMessage event for the purpose of callback lookups.

      **Supporting channels**

      - WhatsApp: Product and ProductLists
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/MoMessageOrder'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Deleted":
    description: |
      This event is triggered when a previously sent MoMessage is deleted by its sender.

      **Supporting channels**

      - WhatsApp
    publish:
      tags:
        - name: "Received messages"
      message:
        $ref: '#/components/messages/MessageStatusDeleted'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Accepted":
    description: |
      This event is triggered when tyntec accepted your message request.

      This happens after the HTTP status code 202 on a messaging request.

      **Supporting channels**

      - All
    publish:
      tags:
        - name: "Delivery updates"
      message:
        $ref: '#/components/messages/MessageStatusAccepted'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Delivered":
    description: |
      This event is triggered when the channel informed us about the successful delivery
      of your message to the recipient.

      **Supporting channels**

      - WhatsApp
      - SMS
      - Viber

    publish:
      tags:
        - name: "Delivery updates"
      message:
        $ref: '#/components/messages/MessageStatusDelivered'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Seen":
    description: |
      This event is triggered when the channel informs that the message was seen by the recipient.

      Depending on the channel, this is a subject of privacy settings by the recipient, eg. WhatsApp.

      **Supporting channels**

      - WhatsApp
      - Viber

    publish:
      tags:
        - name: "Delivery updates"
      message:
        $ref: '#/components/messages/MessageStatusSeen'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Channel Failed":
    description: |
      This event is triggered when a message was not successfully delivered via the channel.

      **Supporting channels**

      - All
    publish:
      tags:
        - name: "Delivery updates"
      message:
        $ref: '#/components/messages/MessageStatusChannelFailed'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Failed":
    description: |
      This event is triggered when the message failed on all configured channels.

      **Supporting channels**

      - All
    publish:
      tags:
        - name: "Delivery updates"
      message:
        $ref: '#/components/messages/MessageStatusFailed'
      bindings:
        http:
          type: request
          method: POST
  "Message Status: Unknown":
    description: |
      This event is triggered when the message status cannot be mapped to any of the others.

      **Supporting channels**

      - All

    publish:
      tags:
        - name: "Delivery updates"
      message:
        $ref: '#/components/messages/MessageStatusUnknown'
      bindings:
        http:
          type: request
          method: POST
  "Call Message":
    description: |
      A call message received by us on the WhatsApp channel and delivered to your system via a webhook provided by your system.

      **Supporting channels**

      - WhatsApp
    publish:
      tags:
        - name: "Calling"
      message:
        $ref: '#/components/messages/CallMessage'
      bindings:
        http:
          type: request
          method: POST
  "Call Status: Ringing":
    description: |
      This event is triggered after the call connect request was successful and it is currently ringing.

      **Supporting channels**

      - WhatsApp
    publish:
      tags:
        - name: "Calling"
      message:
        $ref: '#/components/messages/CallStatusRinging'
      bindings:
        http:
          type: request
          method: POST
  "Call Status: Accepted":
    description: |
      This event is triggered after the end user has accepted your call request.

      **Supporting channels**

      - WhatsApp
    publish:
      tags:
        - name: "Calling"
      message:
        $ref: '#/components/messages/CallStatusAccepted'
      bindings:
        http:
          type: request
          method: POST
  "Call Status: Rejected":
    description: |
      This event is triggered after the end user has rejected your call request.
    publish:
      tags:
        - name: "Calling"
      message:
        $ref: '#/components/messages/CallStatusRejected'
      bindings:
        http:
          type: request
          method: POST
components:
  messages:
    MoMessage:
      payload:
        $ref: '#/components/schemas/MoMessage'
    SMSMoMessage:
      payload:
        $ref: '#/components/schemas/SMSMoMessage'
    WhatsAppMoMessage:
      payload:
        $ref: '#/components/schemas/WhatsAppMoMessage'
    ViberMoMessage:
      payload:
        $ref: '#/components/schemas/ViberMoMessage'
    MoMessagePostback:
      payload:
        $ref: '#/components/schemas/MoMessagePostBack'
    MoMessageOrder:
      payload:
        $ref: '#/components/schemas/MoMessageOrder'
    MessageStatusDeleted:
      payload:
        $ref: '#/components/schemas/MessageStatusDeletedEvent'
    MessageStatusAccepted:
      payload:
        $ref: '#/components/schemas/MessageStatusAccepted'
    MessageStatusDelivered:
      payload:
        $ref: '#/components/schemas/MessageStatusDelivered'
    MessageStatusSeen:
      payload:
        $ref: '#/components/schemas/MessageStatusSeen'
    MessageStatusChannelFailed:
      payload:
        $ref: '#/components/schemas/MessageStatusChannelFailed'
    MessageStatusFailed:
      payload:
        $ref: '#/components/schemas/MessageStatusFailed'
    MessageStatusUnknown:
      payload:
        $ref: '#/components/schemas/MessageStatusUnknown'
    CallMessage:
      payload:
        $ref: '#/components/schemas/WhatsAppCallMessage'
    CallStatusRinging:
      payload:
        $ref: '#/components/schemas/WhatsAppCallRingingStatus'
    CallStatusAccepted:
      payload:
        $ref: '#/components/schemas/WhatsAppCallAcceptedStatus'
    CallStatusRejected:
      payload:
        $ref: '#/components/schemas/WhatsAppCallRejectedStatus'
  schemas:
    APIEvent:
      type: object
      description: Abstract event object produced by the API, such as MessageStatus or MoMessage
      required:
        - event
      properties:
        event:
          $ref: '#/components/schemas/EventTypes'
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source
          example: sms
          enum:
            - sms
            - whatsapp
            - tyntecEcho
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:00
        from:
          type: string
          description: Who triggered this event. Usually a phone number or WhatsApp account ID
          example:
            "491672634678"
      example:
        event: MessageStatus::accepted
        channel: sms
        from: "491672634678"
        timestamp: 2019-06-26T11:41:00
    EventTypes:
      type: string
      description: Determines the event types emitted by the API
      enum:
        - MoMessage
        - MoMessage::Postback
        - MessageStatus::accepted
        - MessageStatus::channelFailed
        - MessageStatus::deleted
        - MessageStatus::delivered
        - MessageStatus::failed
        - MessageStatus::seen
        - MessageStatus::unknown
        - Call::Connect
        - Call::Terminate
        - CallStatus::ringing
        - CallStatus::accepted
        - CallStatus::rejected
    MoMessage:
      type: object
      description: A message received by us and delivered to your system via a webhook provided by your system.
      required:
        - messageId
        - event
        - channel
        - from
        - content
      properties:
        event:
          type: string
          description: Determines which type of event is sent. Always _MoMessage_
          enum:
            - MoMessage
        channel:
          type: string
          description: The channel that triggered the event.
          example: sms
          enum:
            - sms
            - whatsapp
            - tyntecEcho
            - viber
        receivedAt:
          deprecated: true
          type: string
          format: 'date-time'
          description: The point in time when the message was received. **Note** This property will be replaced in the future by the _timestamp_ property from the APIEvent
          example:
            2019-06-26T11:41:00
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the message was received
          example:
            2019-06-26T11:41:00
        messageId:
          type: string
          description: A message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        from:
          type: string
          description: The sender of the message
          example: "49123512314"
        to:
          type: string
          description: The receiver. The format is channel-specific
          example: "49123512315"
        groupId:
          type: string
          description: The group ID from which the event originates. Only present if the message was sent into a group.
          example:
            4923147790717-1564134658
        content:
          $ref: '#/components/schemas/MoContent'
        context:
          $ref: '#/components/schemas/MoContext'
      example:
        messageId: 77185196-664a-43ec-b14a-fe97036c697e
        event: MoMessage
        from: "49123512314"
        to: "49123512315"
        timestamp: 2019-06-26T11:41:00
        channel: viber
        content:
          contentType: text
          text: A simple text message
    MoContent:
      type: object
      description: The content of the mobile-originated message
      required:
        - contentType
      properties:
        contentType:
          type: string
          enum:
            - text
            - media
            - location
            - contacts
            - reaction
            - unknown
          description: What kind of payload is used
          example: media
        text:
          type: string
          description: The received text
          example: Hi, thanks for your support message
        media:
          $ref: '#/components/schemas/MoMedia'
        reaction:
          $ref: '#/components/schemas/MoReaction'
      example:
        contentType: media
        media:
          type: audio
          url: 'https://api.tyntec.com/messaging/v1/chat/media/77185196-664a-43ec-b14a-fe97036c697f'
          mediaId: 77185196-664a-43ec-b14a-fe97036c697f
    MoContext:
      type: object
      description: Contextual information of the mobile-originated message
      properties:
        messageId:
          type: string
          description: The message ID the MoMessage refers to. Usually set when the sender replies to a specific message
          example: 77185196-664a-43ec-b14a-fe97036c697a
        isForwarded:
          type: boolean
          description: Is the message forwarded by the user?
          example: true
        isFrequentlyForwarded:
          type: boolean
          description: Is the message frequently forwarded? The definition of frequently depends on the channel
          example: true
        product:
          $ref: '#/components/schemas/Product'
    Product:
      type: object
      description: A product that got a question
      properties:
        catalogId:
          type: string
          description: The Id of the catalog
          example: "23343-12342"
        productId:
          type: string
          description: The ID or SKU of the product
          example: 123-SKU-12432
        metaProductId:
          type: string
          description: The ID for the product on Meta's side
          example: 12345678
        name:
          type: string
          description: The name of the product
          example: product 123
        description:
          type: string
          description: The description of the product
          example: This is a short description for product 123
        price:
          type: string
          description: The price of the product
          example: €49.99
        currency:
          type: string
          description: The currency of the price
          example: EUR
        salePrice:
          type: string
          description: The discounted price of the product
          example: €24.99
        inventory:
          type: integer
          description: The current stock for the product
          example: 100
        url:
          type: string
          description: The URL of the product
          example: some-valid-url.com/product123
        imageUrl:
          type: string
          description: The image URL of the product
          example: some-valid-url.com/product123.png
    MoReaction:
      type: object
      description: An emoji reaction to a formely sent message
      properties:
        messageId:
          type: string
          description: The messageId of the message this reaction is belonging to.
          example: wamid.HBgMNDkxNzk3ODEwNTM1FQIAEhgUM0E5Mjg5NUVGMEJBMzcwMENERDEB
        emoji:
          type: string
          description: The actual reaction consisting of exactly on emoji, or an empty string indicating deletion of a reaction.
          example: 😀
    MoMedia:
      type: object
      description: Media information
      properties:
        type:
          type: string
          description: What kind of media was received
          enum:
            - image
            - document
            - audio
            - voice
            - video
          example: audio
        url:
          type: string
          description: The URL of the location where the media is stored
          example: https://api.tyntec.com/messaging/v1/chat/media/77185196-664a-43ec-b14a-fe97036c697f
        mediaId:
          type: string
          description: A plain ID of the media to download
          example: 77185196-664a-43ec-b14a-fe97036c697f
        caption:
          type: string
          description: A caption specified by the user or the file name of the document
          example: This is a picture of my cat!
    SMSMoMessage:
      type: object
      description: A message received by us on the SMS channel and delivered to your system via a webhook provided by your system.
      required:
        - messageId
        - event
        - channel
        - from
        - content
      allOf:
        - $ref: '#/components/schemas/MoMessage'
      properties:

        channel:
          type: string
          description: The channel that triggered the event.
          example: sms
          enum:
            - sms
        sms:
          $ref: '#/components/schemas/SMS'
      example:
        messageId: 77185196-664a-43ec-b14a-fe97036c697e
        event: MoMessage
        from: "49123512314"
        to: "49123512315"
        timestamp: 2019-06-26T11:41:00
        channel: sms
        content:
          contentType: text
          text: 'Hi, thanks for your support message'
        sms:
          origin:
            mcc: string
            mnc: string
            ttId: string
          totalPrice: 0
          size: 1
          missingParts: false
          parts:
            - messageId: string
              sentDate: '2019-03-13T13:15:22Z'
              price: 0
              currency: string
              priceEffective: '2019-03-13T13:15:22Z'
              sequenceNumber: 1
    SMS:
      type: object
      description: Details specific to the SMS channel
      properties:
        origin:
          $ref: '#/components/schemas/SMSOrigin'
        totalPrice:
          type: number
          description: The sum of prices for each message part listed in “contentList”.
          example: 0.1
        size:
          type: number
          description: The amount of respective concatenated SMS parts.
          minimum: 1
          maximum: 255
          example: 1
        missingParts:
          type: boolean
          description: True in the case a part of an over-length message was not received by the tyntec platform and the forwarded message text is incomplete.
          default: false
          example: false
        parts:
          type: array
          description: |
            tyntec merges over-length (concatenated) SMS into one string before sending it to your webserver.
            Information for each individual part is collected here
          items:
            $ref: '#/components/schemas/SMSContent'
      example:
        origin:
          mcc: "49"
          mnc: "176"
          ttId: "25"
        totalPrice: 0.1
        size: 1
        missingParts: false
        parts:
          - messageId: 48514285-4e78-4eef-b0c6-4ce68d40c1c3
            sentDate: '2019-03-13T13:15:22Z'
            price: 0
            currency: EUR
            priceEffective: '2019-03-13T13:15:22Z'
            sequenceNumber: 1
    SMSOrigin:
      type: object
      description: Information about the origin of the message
      properties:
        mcc:
          type: string
          description: A representative MCC (Mobile Network Code) of the originating network.
          example: "49"
        mnc:
          type: string
          description: A representative MNC (Mobile Network Code) of the originating network.
          example: "176"
        ttId:
          type: string
          description: The respective tyntec ID of the originating network.
          example: "25"
    SMSContent:
      type: object
      description: SMS channel-specific information
      properties:
        messageId:
          type: string
          description: The unique identifier provided by tyntec for each message part.
          example: 48514285-4e78-4eef-b0c6-4ce68d40c1c3
        sentDate:
          type: string
          description: |
            The time stamp when the SMS was received by the sending MSC (if available).

            or

            The time stamp when the respective message was received by tyntec.
          format: date-time
        price:
          type: number
          description: |
            The price per message from the respective network.

            Negative prices represent payout in favor of tyntec’s customers.
          example: 0.1
        currency:
          type: string
          description: The currency in which the pricing is given; corresponding to the currency of the invoice.
          example: EUR
        priceEffective:
          type: string
          description: The date when the “price” became effective.
          format: date-time
        sequenceNumber:
          type: number
          description: |
            In the case an over-length message is received, tyntec recomposes the full message text before forwarding.
            The “sequenceNumber” indicates the order of the message part.
          minimum: 1
          maximum: 255
          example: 1
    WhatsAppMoMessage:
      type: object
      description: A message received by us on the WhatsApp channel and delivered to your system via a webhook provided by your system.
      required:
        - messageId
        - event
        - channel
        - from
        - content
      allOf:
        - $ref: '#/components/schemas/MoMessage'
      properties:
        channel:
          type: string
          description: The channel that triggered the event.
          example: whatsapp
          enum:
            - whatsapp
        content:
          $ref: '#/components/schemas/MoContent'
        context:
          $ref: '#/components/schemas/MoContext'
        whatsapp:
          $ref: '#/components/schemas/Whatsapp'
      example:
        messageId: 77185196-664a-43ec-b14a-fe97036c697e
        event: MoMessage
        from: "49123512314"
        to: "49123512315"
        timestamp: 2019-06-26T11:41:00
        channel: whatsapp
        content:
          contentType: text
          text: 'Hi, thanks for your support message'
        whatsapp:
          senderName: Peter
          identityKeyHash: DF2lS5v2W6x=
    Whatsapp:
      type: object
      description: Details specific to the WhatsApp channel
      properties:
        senderName:
          type: string
          description: The name of the sender, set in his or her profile
          example: Peter
        identityKeyHash:
          type: string
          description: The customer's hash ID
          example: DF2lS5v2W6x=
      example:
        senderName: Peter
        identityKeyHash: DF2lS5v2W6x=
      additionalProperties: true
    MessageRequestContext:
      type: object
      description: Contextual information for the message request
      properties:
        userContext:
          type: string
          maxLength: 255
          description: |
            Contextual information that is transfered back on delivery notifications.
          example:
            my-message-reference
    ViberMoMessage:
      type: object
      description: A message received by us on the Viber channel and delivered to your system via a webhook provided by your system.
      required:
        - messageId
        - event
        - channel
        - from
        - content
      allOf:
        - $ref: '#/components/schemas/MoMessage'
      properties:
        channel:
          type: string
          description: The channel that triggered the event.
          example: viber
          enum:
            - viber
        content:
          $ref: '#/components/schemas/MoContent'
        context:
          $ref: '#/components/schemas/MoContext'
      example:
        messageId: 77185196-664a-43ec-b14a-fe97036c697e
        event: MoMessage
        from: "49123512314"
        to: "49123512315"
        timestamp: 2019-06-26T11:41:00
        channel: viber
        content:
          contentType: text
          text: 'Hi, thanks for your support message'
    MoMessagePostBack:
      type: object
      description: Postbacks are triggered when a user clicks on a button or interacts with any element that supports this.

        For WhatsApp only Quick Reply buttons trigger this event.
      required:
        - messageId
        - event
        - status
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MoMessage::PostBack_
          enum:
            - MoMessage::Postback
        channel:
          type: string
          description: The channel that triggered the event.
          example: sms
          enum:
            - sms
            - whatsapp
            - tyntecEcho
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the message was received
          example:
            2019-06-26T11:41:00
        messageId:
          type: string
          description: A message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        from:
          type: string
          description: The sender of the message
          example: "49123512314"
        to:
          type: string
          description: The receiver. The format is channel-specific
          example: "49123512315"
        groupId:
          type: string
          description: The group ID from which the event originates. Only present if the message was sent into a group
          example:
            4923147790717-1564134658
        postback:
          $ref: '#/components/schemas/PostBack'
        context:
          $ref: '#/components/schemas/MoContext'
        whatsapp:
          $ref: '#/components/schemas/WhatsAppPostBack'
      example:
        event: MoMessage::PostBack
        messageId: ABGHSRdiRDUxLwIQHWZNgHd-WIdpPHTMERqTgQ
        from: "49123512314"
        to: "49123512315"
        timestamp: 2019-06-26T11:41:00
        channel: whatsapp
        postback:
          data: EventVisited::2020-04-04::WhatsAppFair
        context:
          messageId: 77185196-664a-43ec-b14a-fe97036c697e
        whatsapp:
          senderName: open api sample
          identityKeyHash: DF2lS5v2W6x=
          text: I liked the event
    MoMessageOrder:
      type: object
      description: Orders are triggered when a user places an order from a shopping cart.
      required:
        - messageId
        - event
        - status
        - timestamp
        - order
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MoMessage::Order_
          enum:
            - MoMessage::Order
        channel:
          type: string
          description: The channel that triggered the event.
          example: whatsapp
          enum:
            - whatsapp
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the message was received
          example:
            2019-06-26T11:41:00
        messageId:
          type: string
          description: A message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        from:
          type: string
          description: The sender of the message
          example: "49123512314"
        to:
          type: string
          description: The receiver. The format is channel-specific
          example: "49123512315"
        order:
          $ref: '#/components/schemas/Order'
        context:
          $ref: '#/components/schemas/MoContext'
        whatsapp:
          $ref: '#/components/schemas/Whatsapp'
      example:
        event: MoMessage::Order
        messageId: ABGHSRdiRDUxLwIQHWZNgHd-WIdpPHTMERqTgQ
        from: "49123512314"
        to: "49123512315"
        timestamp: 2019-06-26T11:41:00
        channel: whatsapp
        order:
          catalogId: 2378972934234
          text: Please let me know where I can pick up the order.
          items:
            - productId: 24-2597234-sdfk
              productName: product 1
              description: short description
              quantity: 123
              itemPrice: 123.22
              currency: "EUR"
            - productId: 24-1111134-sdfk
              productName: product 2
              description: short description
              quantity: 1
              itemPrice: 1.22
              currency: "USD"
        whatsapp:
          senderName: Test User
          identityKeyHash: DF2lS5v2W6x=
    PostBack:
      type: object
      properties:
        data:
          type: string
          description: The payload or data that was specified when requesting the button-based message
          example: EventVisited::2020-04-04::WhatsAppFair
    WhatsAppPostBack:
      type: object
      description: Postback data for a WhatsApp quick reply button
      allOf:
        - $ref: '#/components/schemas/Whatsapp'
      properties:
        text:
          type: string
          description: The caption of the button that was clicked
          example: Yes
        title:
          type: string
          description: The title of the interactive item clicked
          example: This is the button you clicked
        description:
          type: string
          description: The description of the interactive item clicked
          example: This is the description of a list item
    Order:
      type: object
      description: Represents an order sent from a channel
      required:
        - items
      properties:
        catalogId:
          type: string
          description: The ID of the catalog the items originate from
          example: 123980-12313123
        text:
          type: string
          description: An optional message from the customer
          example: Hi, please make sure you deliver it in the afternoon
        items:
          type: array
          description: Products placed into the shopping cart for this order
          items:
            $ref: '#/components/schemas/SelectedProduct'
    SelectedProduct:
      type: object
      description: Product selected for an order
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
          description: The ID or SKU of the product selected
          example: test-sku-1234
        productName:
          type: string
          description: Name of the product
          example: product 123
        description:
          type: string
          description: Description of the product
          example: This is a short description for product 123
        quantity:
          type: string
          description: How many items are selected
          example: 1
        itemPrice:
          type: string
          description: The price presented to the customer when choosing the product
          example: 0.11
        currency:
          type: string
          description: The currency of the product's price
          example: EUR
    WhatsAppCallMessage:
      type: object
      description: A call message received by us on the WhatsApp channel and delivered to your system via a webhook provided by your system.
      required:
        - callId
        - event
        - channel
        - from
        - to
        - timestamp
        - direction
      properties:
        callId:
          type: string
          description: The unique identifier provided by Meta for each call.
        event:
          type: string
          description: Determines which type of event is sent.
          enum:
            - Call::Connect
            - Call::Terminate
        channel:
          type: string
          description: The channel that triggered the event.
          enum:
            - whatsapp
        from:
          type: string
          description: The caller phone number of the call, including the country code
        to:
          type: string
          description: The receiver phone number of the call, including the country code
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the call message was received
        direction:
          type: string
          description: The direction of the call being made.
          enum:
            - BUSINESS_INITIATED
            - USER_INITIATED
        session:
          type: object
          description: An object that contains the session description protocol (SDP) type and description language
          properties:
            sdpType:
              type: string
              description: The session description protocol type
              enum:
                - answer
                - offer
            sdp:
              type: string
              description: The SDP info of the device on the other end of the call. The SDP must be compliant with [RFC 8866](https://datatracker.ietf.org/doc/html/rfc8866?fbclid=IwZXh0bgNhZW0CMTEAAR4HJ3Q9N0zf9Gm6wQ9gAnFxJ1tHHQ3kkV63RqBvQO3MpEv5Wp4Cuto4-axx1g_aem_5UvSPiN3fDXy8cEcx-KzQQ).
        status:
          type: string
          description: The final status of the call
          enum:
            - COMPLETED
            - FAILED
        startTime:
          type: string
          format: 'date-time'
          description: The point in time when the call started
        endTime:
          type: string
          format: 'date-time'
          description: The point in time when the call ended
        duration:
          type: number
          description: The duration of the call in seconds
      example:
        event: Call::Connect
        channel: whatsapp
        from: 49123512314
        to: 49123512314
        callId: wacid.HBgMMzA2OTMyODc0NDk3FQIAERgg
        timestamp: 2025-10-01T11:11:11Z
        direction: BUSINESS_INITIATED
        session:
          type: answer
          sdp: <<RFC 8866 SDP>>
    WhatsAppCallRingingStatus:
      type: object
      description: Indicates the call is ringing
      required:
        - messageId
        - event
        - channel
        - timestamp
        - from
        - to
        - status
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _CallStatus::ringing_
          enum:
            - CallStatus::ringing
        messageId:
          type: string
          description: The call ID reference
        channel:
          type: string
          description: The channel that triggered the event. Always _whatsapp_
          enum:
            - whatsapp
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
        from:
          type: string
          description: The caller phone number of the call, including the country code
        to:
          type: string
          description: The receiver phone number of the call, including the country code
        status:
          type: string
          description: The current status of the call. Always _ringing_
          enum:
            - ringing
      example:
        event: CallStatus::ringing
        messageId: wacid.HBgMMzA2OTMyODc0NDk3FQIAERgg
        channel: whatsapp
        from: 49123512314
        to: 49123512314
        status: ringing
        timestamp: 2025-10-01T11:11:11Z
    WhatsAppCallAcceptedStatus:
      type: object
      description: Indicates the call has been accepted by the end user
      required:
        - messageId
        - event
        - channel
        - timestamp
        - from
        - to
        - status
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _CallStatus::accepted_
          enum:
            - CallStatus::accepted
        messageId:
          type: string
          description: The call ID reference
        channel:
          type: string
          description: The channel that triggered the event. Always _whatsapp_
          enum:
            - whatsapp
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
        from:
          type: string
          description: The caller phone number of the call, including the country code
        to:
          type: string
          description: The receiver phone number of the call, including the country code
        status:
          type: string
          description: The current status of the call. Always _accepted_
          enum:
            - accepted
      example:
        event: CallStatus::accepted
        messageId: wacid.HBgMMzA2OTMyODc0NDk3FQIAERgg
        channel: whatsapp
        from: 49123512314
        to: 49123512314
        status: accepted
        timestamp: 2025-10-01T11:11:11Z
    WhatsAppCallRejectedStatus:
      type: object
      description: Indicates the call has been rejected by the end user
      required:
        - messageId
        - event
        - channel
        - timestamp
        - from
        - to
        - status
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _CallStatus::rejected_
          enum:
            - CallStatus::rejected
        messageId:
          type: string
          description: The call ID reference
        channel:
          type: string
          description: The channel that triggered the event. Always _whatsapp_
          enum:
            - whatsapp
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
        from:
          type: string
          description: The caller phone number of the call, including the country code
        to:
          type: string
          description: The receiver phone number of the call, including the country code
        status:
          type: string
          description: The current status of the call. Always _rejected_
          enum:
            - rejected
      example:
        event: CallStatus::rejected
        messageId: wacid.HBgMMzA2OTMyODc0NDk3FQIAERgg
        channel: whatsapp
        from: 49123512314
        to: 49123512314
        status: rejected
        timestamp: 2025-10-01T11:11:11Z
    MessageStatusDeletedEvent:
      type: object
      description: Indicates that a previously sent inbound MoMessage was deleted by the user.
      required:
        - messageId
        - event
        - status
        - channel
        - from
        - to
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent.
          enum:
            - MessageStatus::deleted
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - tyntecEcho
        status:
          description: |
            Indicates the status of the message. Be aware that not all channels support all statuses.

            **Note** This property will be replaced by the property _event_ in a future release.
          deprecated: true
          type: string
          example: seen
          enum:
            - deleted
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
        from:
          type: string
          description: Who triggered this event. Usually the phone number or WhatsApp account ID.
          example:
            "491672634678"
        to:
          type: string
          description: Which channel-specific account ID is the recipient of this event.
          example:
            "4923147790813"
      example:
        event: MessageStatus::deleted
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        status: deleted
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
        from: "491672634678"
        to: "4923147790813"
    MessageStatusAccepted:
      type: object
      description: Indicates the acceptance of the message by the Conversations API
      required:
        - messageId
        - event
        - channel
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MessageStatus::accepted_
          enum:
            - MessageStatus::accepted
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
      example:
        event: MessageStatus::accepted
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
    MessageStatusDelivered:
      type: object
      description: Indicates the delivery of the message to the recipient
      required:
        - messageId
        - event
        - channel
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MessageStatus::delivered_
          enum:
            - MessageStatus::delivered
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
        whatsapp:
          type: object
          description: WhatsApp related additional information. Since 2.12
          properties:
            pricing:
              description: Pricing Information (see https://developers.facebook.com/docs/whatsapp/pricing/updates-to-pricing/#per-message-pricing for detailed field description)
              type: object
              properties:
                billable:
                  type: boolean
                  description: deprecated
                pricingModel:
                  type: string
                  description: from 01.07.25 on, this is always 'PMP'
                type:
                  type: string
                  enum:
                    - regular
                    - free_customer_service
                    - free_entry_point
                category:
                  type: string
                  enum:
                    - authentication
                    - authentication_international
                    - marketing
                    - marketing_lite
                    - utility
                    - service
                    - referral_conversion
            conversation:
              description: Conversation Information
              type: object
              properties:
                conversationId:
                  type: string
                  description: The ID of the conversation generated by WhatsApp
                identityKeyHash:
                  type: string
                  description: The customer's hash ID
                origin:
                  type: string
                  enum:
                    - business_initiated
                    - user_initiated
                    - referral_conversion

      example:
        event: MessageStatus::delivered
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
    MessageStatusSeen:
      type: object
      description: Indicates that the message was seen by the recipient
      required:
        - messageId
        - event
        - channel
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MessageStatus::seen_
          enum:
            - MessageStatus::seen
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
      example:
        event: MessageStatus::seen
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
    MessageStatusChannelFailed:
      type: object
      description: Indicates that the message failed on the particular channel
      required:
        - messageId
        - event
        - channel
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MessageStatus::channelFailed_
          enum:
            - MessageStatus::channelFailed
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
        details:
          type: object
          description: Contains the details, i.e. error code and error message, when encountering an error
          properties:
            code:
              type: string
              description: The error code of the particular error
              example: whatsapp::error::131049
            message:
              type: string
              description: The detailed message returned for the particular error
              example: This message was not delivered to maintain healthy ecosystem engagement. - In order to maintain a healthy ecosystem engagement, the message failed to be delivered.
      example:
        event: MessageStatus::channelFailed
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
        details:
          code: whatsapp::error::131049
          message: This message was not delivered to maintain healthy ecosystem engagement. - In order to maintain a healthy ecosystem engagement, the message failed to be delivered.
    MessageStatusFailed:
      type: object
      description: Indicates that all channels failed.
      required:
        - messageId
        - event
        - channel
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MessageStatus::failed_
          enum:
            - MessageStatus::failed
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
        details:
          type: object
          description: Contains the details, i.e. error code and error message, when encountering an error
          properties:
            code:
              type: string
              description: The error code of the particular error
              example: whatsapp::error::131049
            message:
              type: string
              description: The detailed message returned for the particular error
              example: This message was not delivered to maintain healthy ecosystem engagement. - In order to maintain a healthy ecosystem engagement, the message failed to be delivered.
      example:
        event: MessageStatus::failed
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
        details:
          code: whatsapp::error::131049
          message: This message was not delivered to maintain healthy ecosystem engagement. - In order to maintain a healthy ecosystem engagement, the message failed to be delivered.
    MessageStatusUnknown:
      type: object
      description: Indicates an unforseen message status.
      required:
        - messageId
        - event
        - channel
        - timestamp
      allOf:
        - $ref: '#/components/schemas/APIEvent'
      properties:
        event:
          type: string
          description: Determines which event type is sent. Always _MessageStatus::unknown_
          enum:
            - MessageStatus::unknown
        messageId:
          type: string
          description: A global message ID reference
          example: 77185196-664a-43ec-b14a-fe97036c697f
        channel:
          type: string
          description: The channel that triggered the event. Can be empty in the case of an internal source.
          example: sms
          enum:
            - sms
            - whatsapp
            - viber
        timestamp:
          type: string
          format: 'date-time'
          description: The point in time when the event happened
          example:
            2019-06-26T11:41:28Z
        userContext:
          type: string
          description: Contextual information set on the message request
          example:
            my-message-reference
      example:
        event: MessageStatus::unknown
        messageId: 77185196-664a-43ec-b14a-fe97036c697f
        channel: whatsapp
        userContext: my-message-reference
        timestamp: 2019-06-26T11:41:28Z
