openapi: '3.0.0'
info:
  title: WeChat (Beta)
  description: |
    The Conversations API allows you to easily send messages to your customers via WeChat.

    **Channel specific pre-conditions**

    - *WeChat* : You need to create an official account with WeChat. Please, contact us for details [onboarding@tyntec.com](mailto:onboarding@tyntec.com).

  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-specification-file: wechat.yaml
  x-major-version: v3
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: [ ]
tags:
  - name: "Messaging"
    description: |
      In this section, we guide you on how to send messages, get information about the status and the events happening
      during delivery.
  - name: "WeChat IDs"
    description: |
      List all WeChat IDs configured for your API account.
  - name: "Callback configuration"
    description: |
      In this section, we guide you on how to configure the callbacks on a per-channel basis.
paths:
  /messages:
    post:
      operationId: sendMessage
      summary: Send a message
      tags:
        - "Messaging"
      description: Send messages via this path.
      requestBody:
        description: The message you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              WeChat Text:
                value:
                  from: a cool business
                  to: some number
                  channel: wechat
                  content:
                    contentType: text
                    text: hi there
                  context: my-message-reference
              WeChat Image:
                value:
                  from: a cool business
                  to: some number
                  channel: wechat
                  content:
                    contentType: image
                    image:
                      url: https://www.my.com/image
                      filename: UHUH.jpeg
                  context: my-message-reference
              WeChat Template:
                value:
                  from: a cool business
                  to: some number
                  channel: wechat
                  content:
                    contentType: template
                    template:
                      templateId: wechat-yeah!
                      components:
                        body:
                          - type: text
                            text: Z
                            variable: username
                          - type: text
                            text: 2000 â‚¬
                            variable: amount
      responses:
        202:
          description: The message is accepted by our system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /bulks:
    post:
      operationId: sendABulkMessage
      summary: Send a bulk message
      tags:
        - "Messaging"
      description: Send bulk messages. Bulk messages are defined as ordered messages to **one** receiver.
      requestBody:
        description: The message bulk you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkMessageRequest'
      responses:
        202:
          $ref: '#/components/responses/BulkMessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/wechat:
    get:
      tags:
        - "WeChat IDs"
      summary: List WeChat IDs
      operationId: listAllWeChatChannels
      description: List all WeChat ID configurations available to your API account
      responses:
        200:
          $ref: '#/components/responses/ListAllWeChatChannelsResponse'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/wechat/wechat-ids/{wechat-id}:
    parameters:
      - $ref: '#/components/parameters/WeChatId'
    get:
      tags:
        - "WeChat IDs"
      summary: Read a configuration
      operationId: getWeChatChannelConfig
      description: Returns the specific channel configuration
      responses:
        200:
          $ref: '#/components/responses/WeChatChannelResponse'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/wechat/wechat-ids/{wechat-id}/callbacks:
    parameters:
      - $ref: '#/components/parameters/WeChatId'
    put:
      tags:
        - "Callback configuration"
      summary: Update the callback
      operationId: updateWeChatChannelCallback
      description: Update the callback settings of a specific WeChat ID.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelCallback'
      responses:
        200:
          $ref: '#/components/responses/WeChatChannelResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  parameters:
    WeChatId:
      name: wechat-id
      in: path
      required: true
      description: WeChat ID used for WeChat messaging.
      schema:
        type: string
      example: 23cklsdhf2
  responses:
    BulkMessageResponse:
      description: The response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BulkMessageResponse'
    Default:
      description: The default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.content.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
    Forbidden:
      description: You are attempting to use a sender configuration (WeChat ID) that is not assigned to your tyntec account
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: https://httpstatuses.com/403
            title: Forbidden
            status: 403
    ListAllWeChatChannelsResponse:
      description: A list of WeChat channel configurations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WeChatChannelResponses'
    WeChatChannelResponse:
      description: A WeChat Service ID Configuration
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WeChatChannelResponse'
  schemas:
    Problem:
      $ref: './common.yaml#/components/schemas/Problem'
    MessageResponse:
      $ref: './common.yaml#/components/schemas/MessageResponse'
    BulkMessageResponse:
      $ref: './common.yaml#/components/schemas/BulkMessageResponse'
    MessageRequest:
      type: object
      description: The message you would like to send
      required:
        - to
        - channel
        - from
      properties:
        to:
          type: string
          description: |
            The message's recipient
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: The channel selected for delivery.
          example: WeChat
          enum:
            - wechat
        overrides:
          $ref: 'common.yaml#/components/schemas/MessageRequestOverrides'
        context:
          type: string
          description: The context for this particular message
          maxLength: 125
        content:
          oneOf:
            - $ref: '#/components/schemas/WeChatTextContent'
            - $ref: '#/components/schemas/WeChatImageContent'
            - $ref: '#/components/schemas/WeChatTemplateContent'
      example:
        to: "+123234234"
        from: "545345345"
        channel: "wechat"
        content:
          contentType: text
          text: A simple text message
    BulkMessageRequest:
      type: object
      description: The bulk of messages you would like to send
      required:
        - to
        - channel
        - from
        - messages
      properties:
        to:
          type: string
          description: |
            The message's recipient
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: The channel selected for delivery.
          example: wechat
          enum:
            - wechat
        messages:
          type: array
          maxItems: 20
          minItems: 2
          items:
            oneOf:
              - $ref: '#/components/schemas/WeChatTextContent'
              - $ref: '#/components/schemas/WeChatImageContent'
              - $ref: '#/components/schemas/WeChatTemplateContent'
    WeChatTextContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - text
        text:
          type: string
          maxLength: 3000
    WeChatImageContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - image
        image:
          $ref: '#/components/schemas/WeChatImage'
    WeChatTemplateContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - template
        template:
          $ref: '#/components/schemas/WeChatTemplate'
    WeChatImage:
      type: object
      properties:
        url:
          type: string
        filename:
          type: string
    WeChatTemplate:
      type: object
      properties:
        templateId:
          type: string
        components:
          $ref: '#/components/schemas/WeChatTemplateComponents'
    WeChatTemplateComponents:
      type: object
      properties:
        body:
          type: array
          items:
            $ref: '#/components/schemas/WeChatTemplateTextBody'
    WeChatTemplateTextBody:
      type: object
      properties:
        type:
          type: string
          enum:
            - text
        text:
          type: string
        variable:
          type: string
    WeChatChannelResponse:
      $ref: './configurations.yaml#/components/schemas/WeChatChannelResponse'
    WeChatChannelResponses:
      $ref: './configurations.yaml#/components/schemas/WeChatChannelResponses'
    ChannelCallback:
      $ref: './configurations.yaml#/components/schemas/ChannelCallback'
