openapi: '3.0.0'
info:
  title: WhatsApp
  description: |
    Conversations allows you to easily send messages to your customers via  WhatsApp

    **Channel specific pre-conditions**

    - *WhatsApp* : A WhatsApp Business Account is required in order to use this channel. Please [request access here](https://www.tyntec.com/form-whatsapp-setup-your-waba)


  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-major-version: v3
  x-postman-collection: postman.zip
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: []
paths:
  /messages:
    post:
      operationId: sendMessage
      summary: Send a message
      tags:
        - "Messaging"
      description: Send messages via this path.
      requestBody:
        description: The message you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              WhatsApp Text:
                value:
                  from: a cool business
                  to: some number
                  channel: WhatsApp
                  content:
                    contentType: text
                    text: hi there
                  context: my-message-reference
              WhatsApp Image:
                value:
                  from: a cool business
                  to: some number
                  channel: WhatsApp
                  content:
                    contentType: image
                    image:
                      url: https://www.my.com/image
                      filename: UHUH.jpeg
                  context: my-message-reference
              WhatsApp Template:
                value:
                  from: a cool business
                  to: some number
                  channel: WhatsApp
                  content:
                    contentType: template
                    template:
                      templateId: WhatsApp-yeah!
                      components:
                        body:
                          - type: text
                            text: Z
                            variable: username
                          - type: text
                            text: 2000 €
                            variable: amount
      responses:
        202:
          $ref: '#/components/responses/MessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /bulks:
    post:
      operationId: sendABulkMessage
      summary: Send a bulk message
      tags:
        - "Messaging"
      description: Send bulk messages. Bulk messages are defined as ordered messages to **one** receiver.
      requestBody:
        description: The message bulk you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkMessageRequest'
      responses:
        202:
          $ref: '#/components/responses/BulkMessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  responses:
    MessageResponse:
      description: Response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageResponse'
    BulkMessageResponse:
      description: Response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BulkMessageResponse'
    Default:
      description: Default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.whatsapp.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
    Forbidden:
      description: You attempting to use a number that is not assigned to your account
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: https://httpstatuses.com/403
            title: Forbidden
            status: 403
  schemas:  
    Problem:
      $ref: './common.yaml#/components/schemas/Problem'
    MessageResponse:
      $ref: './common.yaml#/components/schemas/MessageResponse'
    BulkMessageResponse:
      $ref: './common.yaml#/components/schemas/BulkMessageResponse'
    MessageRequest:
      type: object
      description: The message you would like to send
      required:
        - to
        - channel
        - from
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: Channel selected for delivery.
          example: WhatsApp
          items:
            type: string
            enum:
              - whatsapp
        context:
          type: string
          description: Context for this particular message
          maxLength: 125
        content:
          oneOf:
            - $ref: '#/components/schemas/WhatsAppTextContent'
            - $ref: '#/components/schemas/WhatsAppImageContent'
            - $ref: '#/components/schemas/WhatsAppDocumentContent'
            - $ref: '#/components/schemas/WhatsAppVideoContent'
            - $ref: '#/components/schemas/WhatsAppAudioContent'
            - $ref: '#/components/schemas/WhatsAppStickerContent'
            - $ref: '#/components/schemas/WhatsAppLocationContent'
            - $ref: '#/components/schemas/WhatsAppContactsContent'
            - $ref: '#/components/schemas/WhatsAppTemplateContent'
      example:
        to: "+123234234"
        from: "545345345"
        channel: "whatsapp"
        whatsapp:
          contentType: text
          text: A simple text message
    BulkMessageRequest:
      type: object
      description: The bulk of messages you would like to send
      required:
        - to
        - channel
        - from
        - messages
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: Channel selected for delivery.
          example: WhatsApp
          items:
            type: string
            enum:
              - whatsapp
        messages:
          type: array
          maxItems: 20
          minItems: 2
          items:
            oneOf:
            - $ref: '#/components/schemas/WhatsAppTextContent'
            - $ref: '#/components/schemas/WhatsAppImageContent'
            - $ref: '#/components/schemas/WhatsAppDocumentContent'
            - $ref: '#/components/schemas/WhatsAppVideoContent'
            - $ref: '#/components/schemas/WhatsAppAudioContent'
            - $ref: '#/components/schemas/WhatsAppStickerContent'
            - $ref: '#/components/schemas/WhatsAppLocationContent'
            - $ref: '#/components/schemas/WhatsAppContactsContent'
            - $ref: '#/components/schemas/WhatsAppTemplateContent'
    #
    # Content types
    #
    WhatsAppTextContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - text
        text:
          type: string
          maxLength: 4096
    WhatsAppImageContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - image
        image:
          $ref: '#/components/schemas/WhatsAppImage'
    WhatsAppDocumentContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - document
        document:
          $ref: '#/components/schemas/WhatsAppDocument'
    WhatsAppVideoContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - video
        video:
          $ref: '#/components/schemas/WhatsAppVideo'
    WhatsAppAudioContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - audio
        audio:
          $ref: '#/components/schemas/WhatsAppAudio'
    WhatsAppStickerContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - sticker
        sticker:
          $ref: '#/components/schemas/WhatsAppSticker'
    WhatsAppLocationContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - location
        location:
          $ref: '#/components/schemas/WhatsAppLocation'
    WhatsAppContactsContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - contacts
        concats:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
    WhatsAppTemplateContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - template
        template:
          $ref: '#/components/schemas/WhatsAppTemplate'
    #
    # Media
    #
    BaseMedia:
      type: object
      description: |
        Base object handling media definitions for sending.

        One of both properties _url_ or _mediaId_ **must** be set
      properties:
        url:
          type: string
          description: the url of the location where the media is stored
        mediaId:
          type: string
          description: Media id of a previously uploaded media
          format: uuid
    WhatsAppImage:
      type: object
      description: Image media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
      properties:
        caption:
          type: string
    WhatsAppDocument:
      type: object
      description: Document media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
      properties:
        caption:
          type: string
        filename:
          type: string
    WhatsAppVideo:
      type: object
      description: Video media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
      properties:
        caption:
          type: string
    WhatsAppAudio:
      type: object
      description: Audio media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
    WhatsAppSticker:
      type: object
      description: Sticker media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
    #
    # Other types
    #
    WhatsAppLocation:
      type: object
      description: Location received or send
      required:
        - longitude
        - latitude
      properties:
        longitude:
          type: number
          format: double
          description: Longitude part of the coordinate
          example:
            7.4954884
        latitude:
          type: integer
          format: double
          description: Latitude part of the coordinate
          example:
            51.5005765
        name:
          type: string
          maxLength: 256
          description: Optional name
          example:
            tyntec GmbH
        address:
          type: string
          maxLength: 256
          description: Optional address, will only be rendered if name is set
          example:
            tyntec GmbH, Semerteichstraße, Dortmund

    Contact:
      type: object
      description: Contact object
      properties:
        birthday:
          type: string
          description: Birthday of the contact
          example:
            2018-01-01
        addresses:
          type: array
          description: List of addresses assigned to the contact
          items:
            $ref: '#/components/schemas/Address'
        emails:
          type: array
          description: List of emails assigned to the contact
          items:
            $ref: '#/components/schemas/Email'
        ims:
          type: array
          description: List of IMS accounts assigned to the contact
          items:
            $ref: '#/components/schemas/IMS'
        name:
          $ref: '#/components/schemas/Name'
        org:
          $ref: '#/components/schemas/Organisation'
        phones:
          type: array
          description: List of phone numbers assigned to the contact
          items:
            $ref: '#/components/schemas/ContactPhone'
        urls:
          type: array
          description: List of urls assigned to the contact
          items:
            $ref: '#/components/schemas/ContactUrl'
    Address:
      type: object
      description: Address of a contact
      properties:
        city:
          type: string
          description: City name
          example: Dortmund
        country:
          type: string
          description: Full country name
          example: Germany
        countryCode:
          type: string
          description: Two-letter code abbreviation
          example: de
        state:
          type: string
          description: State abbreviation
          example: NRW
        street:
          type: string
          description: Street name and number
        type:
          type: string
          description: Type of the address
          example: WORK
        zip:
          type: string
          description: ZIP or postal code
          example: 44231
    Email:
      type: object
      description: Email of the contact
      properties:
        email:
          type: string
          description: Email address
          example: whatsapp@tyntec.com
        type:
          type: string
          description: Type of the email
          example: WORK
    IMS:
      type: object
      description: IMS of the contact
      properties:
        service:
          type: string
          description: Type of the email
          example: WhatsApp
        userId:
          type: string
          description: IMS user id
          example: 123123123
    Name:
      type: object
      description: |
        The name of a contact. Apart from the property ``formattedName`` at least one of the other must be set
      required:
        - formattedName
      properties:
        prefix:
          type: string
          description: Prefix of the contacts name
          example: Mr.
        firstName:
          type: string
          description: First name of the contact
          example: Peter
        middleName:
          type: string
          description: Middle name of the contact
          example: Michael
        lastName:
          type: string
          description: Last name of the contact
          example: Tyntec
        suffix:
          type: string
          description: Suffix of the contacts name
          example: senior
        formattedName:
          type: string
          description: Completely formatted name
          example: Mr. Peter Michael Tyntec senior
    Organisation:
      type: object
      description: Organisation associated with the contact
      properties:
        company:
          type: string
          description: Name of the contact's company
          example: tyntec GmbH
        department:
          type: string
          description: Name of the contact's department
          example: Development
        title:
          type: string
          description: Contact's business title
          example: API Guardian
    ContactPhone:
      type: object
      description: Phone entry of a contact
      properties:
        phone:
          type: string
          description: Phone number
          example: +49 231 477 90 813
        type:
          type: string
          description: Type of phone number
          example: WORK
    ContactUrl:
      type: object
      description: URL of a contact
      properties:
        url:
          type: string
          description: URL of a contact
          example: https://www.tyntec.com
        type:
          type: string
          description: Type of URL
          example: WORK

    # Templated messages

    WhatsAppTemplate:
      type: object
      properties:
        templateId:
          type: string
        language:
          type: string
        components:
          $ref: '#/components/schemas/WhatsAppTemplateComponents'
    WhatsAppTemplateComponents:
      type: object
      properties:
        header:
          type: array
          minItems: 0
          maxItems: 1
          items:
            oneOf:
            - $ref: '#/components/schemas/WhatsAppTemplateTextHeaderComponent'
            - $ref: '#/components/schemas/WhatsAppTemplateImageHeaderComponent'
            - $ref: '#/components/schemas/WhatsAppTemplateVideoHeaderComponent'
            - $ref: '#/components/schemas/WhatsAppTemplateDocumentHeaderComponent'
            - $ref: '#/components/schemas/WhatsAppTemplateLocationHeaderComponent'
        body:
          type: array
          minItems: 0
          maxItems: 1
          items:
            $ref: '#/components/schemas/WhatsAppTemplateTextBodyComponent'
        button:
          oneOf:
            - $ref: '#/components/schemas/WhatsAppQuickReplyButtons'
            - $ref: '#/components/schemas/WhatsAppCallToActionButtons'
    WhatsAppTemplateTextHeaderComponent:
      type: object
      properties:
        type:
          type: string
          enum:
            - text
        text:
          type: string
          maxLength: 60
    WhatsAppTemplateImageHeaderComponent:
      type: object
      properties:
        type:
          type: string
          enum:
            - image
        image:
          $ref: '#/components/schemas/WhatsAppTemplateMediaHeader'
    WhatsAppTemplateVideoHeaderComponent:
      type: object
      properties:
        type:
          type: string
          enum:
            - video
        video:
          $ref: '#/components/schemas/WhatsAppTemplateMediaHeader'
    WhatsAppTemplateDocumentHeaderComponent:
      type: object
      properties:
        type:
          type: string
          enum:
            - document
        document:
          $ref: '#/components/schemas/WhatsAppTemplateDocumentHeader'
    WhatsAppTemplateLocationHeaderComponent:
      type: object
      properties:
        type:
          type: string
          enum:
            - document
        document:
          $ref: '#/components/schemas/WhatsAppLocation'
    WhatsAppTemplateMediaHeader:
      type: object
      description: Document media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
    WhatsAppTemplateDocumentHeader:
      type: object
      description: Document media specification
      allOf:
        - $ref: '#/components/schemas/BaseMedia'
      properties:
        filename:
          type: string
          description: Additional info for the filename to be displayed.
          example: Test PDF

    WhatsAppTemplateTextBodyComponent:
      type: object
      properties:
        type:
          type: string
          enum:
            - text
        text:
          type: string
    WhatsAppQuickReplyButtons:
      type: array
      minItems: 0
      maxItems: 3
      items:
        $ref: '#/components/schemas/QuickReplyButtonComponent'
    WhatsAppCallToActionButtons:
      type: array
      minItems: 0
      maxItems: 1
      items:
        $ref: '#/components/schemas/UrlButtonComponent'
    QuickReplyButtonComponent:
      type: object
      description: This type can be used up to three times
      properties:
        type:
          type: string
          description: Determines the type of the component. Always _button_.
          enum:
            - button
        subType:
          type: string
          description: Determines the sub type of the button. Always _quick_reply_.
          enum:
            - quick_reply
        index:
          type: number
          description: Determines the index of the button that should be enhanced with the payload.
          minimum: 0
          maximum: 2
        parameters:
          type: array
          description: Parameter for this quick reply button
          items:
            properties:
              type:
                type: string
                description: Determines the type of the parameter. Always _payload_.
                enum:
                  - payload
              payload:
                type: string
                maxLength: 128
                description: Payload for this quick reply button. Sent back on the `MoMessage::PostBack` event
          minItems: 0
          maxItems: 1
    UrlButtonComponent:
      type: object
      description: This type can be used up to one time
      properties:
        type:
          type: string
          description: Determines the type of the component. Always _button_.
          enum:
            - button
        subType:
          type: string
          description: Determines the type of the component. Always _url_.
          enum:
            - url
        index:
          type: number
          description: Determines the index of the button that should be enhanced with a custom parameter
          minimum: 0
          maximum: 1
        parameters:
          type: array
          description: Parameters to be used in Button's URL
          items:
            properties:
              type:
                type: string
                description: Determines the type of the parameter. Always _text_.
                enum:
                  - text
              text:
                type: string
                maxLength: 2000
                description: Which text should be append to a dynamic URL. **Note** the requested templates url button must end with {{1}}.
          minItems: 0
          maxItems: 1